problem_one.out: problem_one.c
	gcc -O2 -Wall -Wextra -pedantic -std=c99 problem_one.c -o problem_one.out

run_one: problem_one.out problem_one.c
	./problem_one.out

problem_two.out: problem_two.c
	gcc -O2 -Wall -Wextra -pedantic -std=c99 problem_two.c -o problem_two.out

run_two: problem_two.out problem_two.c
	./problem_two.out
